// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNyVYboEeA_X1iGnF7BfbXQiduYndN1E',
    appId: '1:939783069297:web:12d8906abf78765960c5d0',
    messagingSenderId: '939783069297',
    projectId: 'mypathapp-820de',
    authDomain: 'mypathapp-820de.firebaseapp.com',
    storageBucket: 'mypathapp-820de.firebasestorage.app',
    measurementId: 'G-CK5ZH14KWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3oOUy9FMJ31ubAUNdQUJBe7IkouYJULU',
    appId: '1:939783069297:android:a9b12235e876854260c5d0',
    messagingSenderId: '939783069297',
    projectId: 'mypathapp-820de',
    storageBucket: 'mypathapp-820de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPulvy1pg0txVfwEYjp-2zAsj3wGi2Hhc',
    appId: '1:939783069297:ios:a3149cc4b25237d960c5d0',
    messagingSenderId: '939783069297',
    projectId: 'mypathapp-820de',
    storageBucket: 'mypathapp-820de.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPulvy1pg0txVfwEYjp-2zAsj3wGi2Hhc',
    appId: '1:939783069297:ios:a3149cc4b25237d960c5d0',
    messagingSenderId: '939783069297',
    projectId: 'mypathapp-820de',
    storageBucket: 'mypathapp-820de.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXNyVYboEeA_X1iGnF7BfbXQiduYndN1E',
    appId: '1:939783069297:web:2fbae99d78deea9a60c5d0',
    messagingSenderId: '939783069297',
    projectId: 'mypathapp-820de',
    authDomain: 'mypathapp-820de.firebaseapp.com',
    storageBucket: 'mypathapp-820de.firebasestorage.app',
    measurementId: 'G-XFD2DFB8ZE',
  );

}